name: mood_tracer_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  go_router: ^14.1.0
  device_preview: ^1.2.0
  cupertino_icons: ^1.0.8
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
assets:
- assets/edit_profile.png
- assets/history.png
- assets/home.png
- assets/login_berhasil.png
- assets/login_tablet.png
- assets/login.png
- assets/Manajemen_akun.png
- assets/mode_gelap.png
- assets/profile.png
- assets/setting.png
- assets/signup.png
- assets/simpan_mood.png